# Generated by Django 5.2.7 on 2025-11-17 12:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bivalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Bivalvo',
                'verbose_name_plural': 'Bivalvos',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('geopoligono', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('nombre_sector', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('zonas', models.ManyToManyField(related_name='sectores', to='dashboard.zona')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialTurbidez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('marca_tiempo', models.DateTimeField(db_index=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turbideces', to='dashboard.sector')),
            ],
            options={
                'verbose_name': 'Historial de Turbidez',
                'verbose_name_plural': 'Historiales de Turbidez',
                'ordering': ['-marca_tiempo'],
                'indexes': [models.Index(fields=['sector', '-marca_tiempo'], name='dashboard_h_sector__91c63b_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(100)])),
                ('marca_tiempo', models.DateTimeField(db_index=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperaturas', to='dashboard.sector')),
            ],
            options={
                'verbose_name': 'Historial de Temperatura',
                'verbose_name_plural': 'Historiales de Temperatura',
                'ordering': ['-marca_tiempo'],
                'indexes': [models.Index(fields=['sector', '-marca_tiempo'], name='dashboard_h_sector__70db83_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialSalinidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('marca_tiempo', models.DateTimeField(db_index=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salinidades', to='dashboard.sector')),
            ],
            options={
                'verbose_name': 'Historial de Salinidad',
                'verbose_name_plural': 'Historiales de Salinidad',
                'ordering': ['-marca_tiempo'],
                'indexes': [models.Index(fields=['sector', '-marca_tiempo'], name='dashboard_h_sector__ea3c63_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialPh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)])),
                ('marca_tiempo', models.DateTimeField(db_index=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_registros', to='dashboard.sector')),
            ],
            options={
                'verbose_name': 'Historial de pH',
                'verbose_name_plural': 'Historiales de pH',
                'ordering': ['-marca_tiempo'],
                'indexes': [models.Index(fields=['sector', '-marca_tiempo'], name='dashboard_h_sector__fda76b_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialHumedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('marca_tiempo', models.DateTimeField(db_index=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humedades', to='dashboard.sector')),
            ],
            options={
                'verbose_name': 'Historial de Humedad',
                'verbose_name_plural': 'Historiales de Humedad',
                'ordering': ['-marca_tiempo'],
                'indexes': [models.Index(fields=['sector', '-marca_tiempo'], name='dashboard_h_sector__93ad52_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialClasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_tiempo', models.DateTimeField(db_index=True)),
                ('bivalvo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='dashboard.bivalvo')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='dashboard.sector')),
            ],
            options={
                'verbose_name': 'Historial de Clasificación',
                'verbose_name_plural': 'Historiales de Clasificación',
                'ordering': ['-marca_tiempo'],
                'indexes': [models.Index(fields=['sector', '-marca_tiempo'], name='dashboard_h_sector__9333bc_idx'), models.Index(fields=['bivalvo', '-marca_tiempo'], name='dashboard_h_bivalvo_26700f_idx')],
                'constraints': [models.UniqueConstraint(fields=('sector', 'bivalvo', 'marca_tiempo'), name='unique_clasificacion')],
            },
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['latitud', 'longitud'], name='dashboard_s_latitud_a9df06_idx'),
        ),
    ]
