# Generated by Django 5.2.7 on 2025-10-30 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bivalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialTurbidez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('marca_tiempo', models.DateTimeField()),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sector')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marca_tiempo', models.DateTimeField()),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sector')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialSalinidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('marca_tiempo', models.DateTimeField()),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sector')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('marca_tiempo', models.DateTimeField()),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sector')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialHumedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('marca_tiempo', models.DateTimeField()),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sector')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialClasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_tiempo', models.DateTimeField()),
                ('bivalvo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.bivalvo')),
                ('sector_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.sector')),
            ],
        ),
    ]
