# Generated by Django 5.2.7 on 2025-10-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistorialClasificacion',
            new_name='Historial_Clasificacion',
        ),
        migrations.RenameModel(
            old_name='HistorialTemperatura',
            new_name='Historial_Humedad',
        ),
        migrations.RenameModel(
            old_name='HistorialSalinidad',
            new_name='Historial_Ph',
        ),
        migrations.RenameModel(
            old_name='HistorialPh',
            new_name='Historial_Salinidad',
        ),
        migrations.RenameModel(
            old_name='HistorialHumedad',
            new_name='Historial_Temperatura',
        ),
        migrations.RenameModel(
            old_name='HistorialTurbidez',
            new_name='Historial_Turbidez',
        ),
    ]
